
INPUT_SECTION_CONTEXT = "CONTEXT"
INPUT_SECTION_QUESTION = "QUESTION"
INPUT_SECTION_CONTEXT_ITEM_RESULT = "Results"
INPUT_SECTION_CONTEXT_ITEMS_SEPARATOR = "|||||"

SECTION_PREVIOUS_ACTIONS = "PreviousActions"
SECTION_INTERNAL_THOUGHT = "InternalThought"
SECTION_ENOUGH_INFO = "EnoughInfo"
SECTION_ANSWER = "Answer"
SECTION_WEB_SEARCH = "WebSearch"
